### ISSUE TITLE
broken for flutter 2.8

### ISSUE THREAD

**Issue by felix-ht** [yako-dev/flutter-settings-ui#102] opened 2021-12-10 13:21 UTC
If flutter 2.8 we get the error: 
```
: Error: A value of type 'ListTileThemeData' can't be assigned to a variable of type 'ListTileTheme'.
../…/src/cupertino_settings_item.dart:76
- 'ListTileThemeData' is from 'package:flutter/src/material/list_tile.dart' ('../../flutter/packages/flutter/lib/src/material/list_tile.dart').
package:flutter/…/material/list_tile.dart:1
- 'ListTileTheme' is from 'package:flutter/src/material/list_tile.dart' ('../../flutter/packages/flutter/lib/src/material/list_tile.dart').
package:flutter/…/material/list_tile.dart:1
    final ListTileTheme tileTheme = ListTileTheme.of(context);
```

Fixed with
https://github.com/yako-dev/flutter-settings-ui/blob/dd14938d5c58863b0a0f32897267d35ce6ea8ba4/lib/src/cupertino_settings_item.dart#L80
changed to (and later references changed ListTileThemeData)
`final tileTheme = ListTileTheme.of(context);`

in general i would recommend to avoid typing these types kind of assignments explicitly

**Comment by HobbyDroider** [comment] 2021-12-11 15:26
The mentioned later reference is in the signature of the method `_iconColor(ThemeData theme, ListTileTheme tileTheme)` change that to `_iconColor(ThemeData theme, ListTileTheme tileTheme)` as a quick fix.

**Comment by superkeka** [comment] 2021-12-11 21:35
Same issue

**Comment by leszekru** [comment] 2021-12-11 22:03
Yes, it's broken and 'easy' to quick-fix...

**Comment by azazadev** [comment] 2021-12-12 12:02
same issue

**Comment by iakrevetkho** [comment] 2021-12-13 04:37
same issue

**Comment by cirediew** [comment] 2021-12-13 10:09
Duplicate of #99 Pull request is waiting to be merged #101

**Comment by elirehema** [comment] 2021-12-15 22:26
Just check this comment here https://github.com/yako-dev/flutter-settings-ui/pull/101#issuecomment-993603256 it can help

**Comment by mrinvestment** [comment] 2021-12-16 20:29
same issue ... :-(

**Comment by ryandailey100** [comment] 2021-12-28 22:47
@yadaniyil Please merge fix & release update

**Comment by cirediew** [comment] 2021-12-31 10:26
@ryandailey100 as stated before, read this https://github.com/yako-dev/flutter-settings-ui/pull/101#issuecomment-993603256

**Comment by yadaniyil** [comment] 2022-01-09 11:21
Hey @felix-ht @HobbyDroider @superkeka @leszekru @azazadev @cirediew @elirehema @mrinvestment @ryandailey100 . There is a new 2.0.0 version of the package, could you please if your issue is fixed there? Thanks :)

**Comment by elirehema** [comment] 2022-01-09 14:04
Thanks, @yadaniyil, unfortunately, I have followed the instruction in[ #101 comment](https://github.com/yako-dev/flutter-settings-ui/pull/101#issuecomment-993603256)

**Comment by cirediew** [comment] 2022-01-10 15:17
@yadaniyil This issue seems to be fixed for me on 2.0.1. Thank you

**Closed** 2022-01-24 14:39 UTC
